### ISSUE TITLE
Docker-compose vs kaniko

### ISSUE THREAD

**Issue by MR-GREEN1337** [phospho-app/phospho#880]
Hi,
I've been amusing myself by looking at your code repo for the past few weeks, and I've gotta say you've done a great job. But  I kept looking at where docker-compose is used in deployement, is it only for local run? have you chosen kaniko as a replacement? and how is kaniko better, since it's used in your cloudbuild.yaml files.

**Comment by Pierre-LouisBJT** [comment]
Hi, 
indeed we do not used the docker-compose in production. Its main purpose is to enable anyone to quickly have a preview of phospho up and running on their machine. So you are right, it is only for local runs.
Are you encountering any specific issue we can help you with?

**Comment by MR-GREEN1337** [comment]
Hi,
I was just trying to understand the entire structure. It's an excellent case study for system design. Thanks a lot!

**Comment by oulianov** [comment]
Hope this helps !
Note : you can also use the [Porter](https://www.porter.run) deployment scripts
Feel free to reach out if you need anything else.
